apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
  namespace: oppe2-app
spec:
  selector:
    app: fraud-detection-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer
