    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: telemetry-access
      namespace: oppe2-app
      annotations:
        iam.gke.io/gcp-service-account: telemetry-access@just-skyline-461512-a8.iam.gserviceaccount.com
    
